// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NeedlePb struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	HaystackId           uint32   `protobuf:"fixed32,3,opt,name=HaystackId,proto3" json:"HaystackId,omitempty"`
	Offset               uint32   `protobuf:"fixed32,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Flags                uint32   `protobuf:"fixed32,5,opt,name=Flags,proto3" json:"Flags,omitempty"`
	FileName             string   `protobuf:"bytes,6,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             uint32   `protobuf:"fixed32,7,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	MimeType             string   `protobuf:"bytes,8,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	CheckSum             uint32   `protobuf:"fixed32,9,opt,name=CheckSum,proto3" json:"CheckSum,omitempty"`
	FileBytes            []byte   `protobuf:"bytes,10,opt,name=FileBytes,proto3" json:"FileBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeedlePb) Reset()         { *m = NeedlePb{} }
func (m *NeedlePb) String() string { return proto.CompactTextString(m) }
func (*NeedlePb) ProtoMessage()    {}
func (*NeedlePb) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *NeedlePb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeedlePb.Unmarshal(m, b)
}
func (m *NeedlePb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeedlePb.Marshal(b, m, deterministic)
}
func (m *NeedlePb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeedlePb.Merge(m, src)
}
func (m *NeedlePb) XXX_Size() int {
	return xxx_messageInfo_NeedlePb.Size(m)
}
func (m *NeedlePb) XXX_DiscardUnknown() {
	xxx_messageInfo_NeedlePb.DiscardUnknown(m)
}

var xxx_messageInfo_NeedlePb proto.InternalMessageInfo

func (m *NeedlePb) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NeedlePb) GetHaystackId() uint32 {
	if m != nil {
		return m.HaystackId
	}
	return 0
}

func (m *NeedlePb) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *NeedlePb) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *NeedlePb) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *NeedlePb) GetFileSize() uint32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *NeedlePb) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *NeedlePb) GetCheckSum() uint32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

func (m *NeedlePb) GetFileBytes() []byte {
	if m != nil {
		return m.FileBytes
	}
	return nil
}

type Node struct {
	StoreName            string   `protobuf:"bytes,1,opt,name=StoreName,proto3" json:"StoreName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

type NodeStatus struct {
	Capacity             uint64   `protobuf:"varint,1,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	Used                 uint64   `protobuf:"varint,2,opt,name=Used,proto3" json:"Used,omitempty"`
	FileCount            uint32   `protobuf:"fixed32,3,opt,name=FileCount,proto3" json:"FileCount,omitempty"`
	StartTs              uint64   `protobuf:"varint,4,opt,name=StartTs,proto3" json:"StartTs,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *NodeStatus) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *NodeStatus) GetFileCount() uint32 {
	if m != nil {
		return m.FileCount
	}
	return 0
}

func (m *NodeStatus) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *NodeStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*NeedlePb)(nil), "pb.NeedlePb")
	proto.RegisterType((*Node)(nil), "pb.Node")
	proto.RegisterType((*NodeStatus)(nil), "pb.NodeStatus")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6a, 0xe3, 0x30,
	0x10, 0x86, 0x23, 0xaf, 0xe3, 0xd8, 0x43, 0xc8, 0x41, 0x2c, 0x8b, 0x08, 0xcb, 0x62, 0x4c, 0x0e,
	0xde, 0x4b, 0x0e, 0xed, 0x1b, 0x34, 0x10, 0x9a, 0x43, 0xd3, 0x22, 0xa7, 0xf4, 0x2c, 0x5b, 0x93,
	0xd6, 0x24, 0xa9, 0x85, 0xad, 0x14, 0xdc, 0x17, 0x68, 0x9f, 0xb8, 0xe7, 0x22, 0xd9, 0x4a, 0xda,
	0x5b, 0x6f, 0xf3, 0xfd, 0xff, 0xcc, 0xf0, 0x6b, 0x6c, 0x88, 0x6a, 0x55, 0xcc, 0x55, 0x5d, 0xe9,
	0x8a, 0x7a, 0x2a, 0x4f, 0x3e, 0x08, 0x84, 0x6b, 0x44, 0xb9, 0xc7, 0xbb, 0x9c, 0x4e, 0xc0, 0x5b,
	0x49, 0x46, 0x62, 0x92, 0xfa, 0xdc, 0x5b, 0x49, 0xfa, 0x0f, 0xe0, 0x5a, 0xb4, 0x8d, 0x16, 0xc5,
	0x6e, 0x25, 0xd9, 0xaf, 0x98, 0xa4, 0x23, 0xfe, 0x45, 0xa1, 0x7f, 0x20, 0xb8, 0xdd, 0x6e, 0x1b,
	0xd4, 0xcc, 0xb7, 0x5e, 0x4f, 0xf4, 0x37, 0x0c, 0x97, 0x7b, 0xf1, 0xd8, 0xb0, 0xa1, 0x95, 0x3b,
	0xa0, 0x53, 0x08, 0x97, 0xe5, 0x1e, 0xd7, 0xe2, 0x80, 0x2c, 0x88, 0x49, 0x1a, 0xf1, 0x13, 0x3b,
	0x2f, 0x2b, 0x5f, 0x91, 0x8d, 0xec, 0xd0, 0x89, 0x8d, 0x77, 0x53, 0x1e, 0x70, 0xd3, 0x2a, 0x64,
	0x61, 0x37, 0xe7, 0xd8, 0x78, 0x8b, 0x27, 0x2c, 0x76, 0xd9, 0xf1, 0xc0, 0xa2, 0x6e, 0xce, 0x31,
	0xfd, 0x0b, 0x91, 0xd9, 0x71, 0xd5, 0x6a, 0x6c, 0x18, 0xc4, 0x24, 0x1d, 0xf3, 0xb3, 0x90, 0xcc,
	0xc0, 0x5f, 0x57, 0x12, 0x4d, 0x57, 0xa6, 0xab, 0xba, 0x8b, 0x45, 0xec, 0xfa, 0xb3, 0x90, 0xbc,
	0x13, 0x00, 0xd3, 0x96, 0x69, 0xa1, 0x8f, 0xf6, 0x09, 0x0b, 0xa1, 0x44, 0x51, 0xea, 0xb6, 0x3f,
	0xd3, 0x89, 0x29, 0x05, 0xff, 0xbe, 0x41, 0xc9, 0x3c, 0xab, 0xdb, 0xda, 0x45, 0x58, 0x54, 0xc7,
	0x67, 0xdd, 0xdf, 0xef, 0x2c, 0x50, 0x06, 0xa3, 0x4c, 0x8b, 0x5a, 0x6f, 0x1a, 0x7b, 0x3f, 0x9f,
	0x3b, 0x34, 0xbb, 0x6c, 0x9e, 0xa1, 0xcd, 0x63, 0xeb, 0x8b, 0x37, 0x02, 0xc0, 0x55, 0x91, 0x61,
	0xfd, 0x52, 0x16, 0x48, 0xff, 0x43, 0xf4, 0x50, 0x97, 0x1a, 0xcd, 0x3a, 0x3a, 0x9e, 0xab, 0x7c,
	0xee, 0x3e, 0xe3, 0xf4, 0x1b, 0x25, 0x03, 0x9a, 0x42, 0xc8, 0x51, 0xc8, 0x1f, 0x74, 0xce, 0x20,
	0xe8, 0x5f, 0x1a, 0x5a, 0xa7, 0x92, 0x38, 0x9d, 0xb8, 0xaa, 0x73, 0x92, 0x41, 0x1e, 0xd8, 0xdf,
	0xe7, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x33, 0xb8, 0x7c, 0x6b, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RpcServiceClient is the client API for RpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcServiceClient interface {
	// Sends a greeting
	WriteFile(ctx context.Context, in *NeedlePb, opts ...grpc.CallOption) (*NeedlePb, error)
	ReadFile(ctx context.Context, in *NeedlePb, opts ...grpc.CallOption) (*NeedlePb, error)
	Status(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeStatus, error)
}

type rpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewRpcServiceClient(cc *grpc.ClientConn) RpcServiceClient {
	return &rpcServiceClient{cc}
}

func (c *rpcServiceClient) WriteFile(ctx context.Context, in *NeedlePb, opts ...grpc.CallOption) (*NeedlePb, error) {
	out := new(NeedlePb)
	err := c.cc.Invoke(ctx, "/pb.RpcService/WriteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ReadFile(ctx context.Context, in *NeedlePb, opts ...grpc.CallOption) (*NeedlePb, error) {
	out := new(NeedlePb)
	err := c.cc.Invoke(ctx, "/pb.RpcService/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) Status(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, "/pb.RpcService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServiceServer is the server API for RpcService service.
type RpcServiceServer interface {
	// Sends a greeting
	WriteFile(context.Context, *NeedlePb) (*NeedlePb, error)
	ReadFile(context.Context, *NeedlePb) (*NeedlePb, error)
	Status(context.Context, *Node) (*NodeStatus, error)
}

func RegisterRpcServiceServer(s *grpc.Server, srv RpcServiceServer) {
	s.RegisterService(&_RpcService_serviceDesc, srv)
}

func _RpcService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeedlePb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcService/WriteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).WriteFile(ctx, req.(*NeedlePb))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeedlePb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcService/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).ReadFile(ctx, req.(*NeedlePb))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).Status(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RpcService",
	HandlerType: (*RpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteFile",
			Handler:    _RpcService_WriteFile_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _RpcService_ReadFile_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RpcService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
